from pathlib import Path
p=Path('src/lib/ficha.ts'); s=p.read_text()
def once(old,new,label):
    global s
    if old not in s: raise SystemExit(f'marcador não encontrado: {label}')
    s=s.replace(old,new,1)
marker='/** Deixa a ficha no padrão do Fragrantica Brasil e corrige números inconsistentes. */'
helpers='''/** Vetores que já apareceram em prompts antigos e não podem ser aceitos como dado pesquisado. */
const FIXACAO_EXEMPLOS_ANTIGOS = new Set(["0,0,100,0,0", "42,194,855,179,23", "5,15,55,20,5"]);
const PROJECAO_EXEMPLOS_ANTIGOS = new Set(["120,610,240,35"]);
const assinaturaVotos = (v?: number[] | null) => (v ?? []).map((x) => Math.round(Number(x) || 0)).join(",");
const votosSuspeitos = (v?: Partial<Votos> | null) => FIXACAO_EXEMPLOS_ANTIGOS.has(assinaturaVotos(v?.fixacao)) || PROJECAO_EXEMPLOS_ANTIGOS.has(assinaturaVotos(v?.projecao));
function invalidarVotos(f: FichaIA): FichaIA {
  const revisar = new Set(f.revisar ?? []); revisar.add("votos");
  return { ...f, votos: { ...f.votos, fixacao: [], projecao: [] }, fixacaoH: 0, projecaoM: 0, revisar: [...revisar], completar: true };
}
async function votosDuplicadosNoAcervo(nome: string, casa: string, fixacao?: number[] | null, projecao?: number[] | null) {
  if (!temVotos(fixacao) || !temVotos(projecao)) return false;
  const fx=assinaturaVotos(fixacao), pj=assinaturaVotos(projecao); const { perfumes }=await carregarAcervo();
  return [...perfumes.values()].some((p)=> normal(p.nome)!==normal(nome) || normal(p.casa)!==normal(casa) ? assinaturaVotos(p.votos?.fixacao)===fx && assinaturaVotos(p.votos?.projecao)===pj : false);
}

'''+marker
once(marker,helpers,'helpers')
once('''  const votos = votosDe(f.votos as Partial<Votos>, f.votos?.ocasioes?.length ? f.votos.ocasioes : OCASIOES);\n  if (!votos || !temVotos(votos.fixacao) || !temVotos(votos.projecao)) revisar.add("votos");''','''  const votosLidos = votosDe(f.votos as Partial<Votos>, f.votos?.ocasioes?.length ? f.votos.ocasioes : OCASIOES);\n  const votos = votosLidos && !votosSuspeitos(votosLidos) ? votosLidos : null;\n  if (!votos || !temVotos(votos.fixacao) || !temVotos(votos.projecao)) revisar.add("votos");''','finalizar votos')
once('''    votos: votos ?? f.votos,\n    fixacaoH: votos && temVotos(votos.fixacao) ? horasDosVotos(votos.fixacao) : f.fixacaoH,\n    projecaoM: votos && temVotos(votos.projecao) ? metrosDosVotos(votos.projecao) : f.projecaoM,''','''    votos: votos ?? { ...f.votos, fixacao: [], projecao: [] },\n    fixacaoH: votos && temVotos(votos.fixacao) ? horasDosVotos(votos.fixacao) : 0,\n    projecaoM: votos && temVotos(votos.projecao) ? metrosDosVotos(votos.projecao) : 0,''','finalizar retorno')
once('''    const fx = (data.votos as { fixacao?: number[] } | null)?.fixacao ?? [];\n    // [0,0,100,0,0] era o valor de reserva antigo (votos não encontrados): pesquisa de novo\n    if (!ac.some((a) => a.valor > 0) || !fx.some((x) => x > 0) || fx.join() === "0,0,100,0,0") return null;''','''    const fx = (data.votos as { fixacao?: number[]; projecao?: number[] } | null)?.fixacao ?? [];\n    const pj = (data.votos as { fixacao?: number[]; projecao?: number[] } | null)?.projecao ?? [];\n    if (!ac.some((a) => a.valor > 0) || !fx.some((x) => x > 0) || votosSuspeitos({ fixacao: fx, projecao: pj }) || await votosDuplicadosNoAcervo(nome, casa, fx, pj)) return null;''','fichaSalva')
once('''export async function completarFicha(f: FichaIA): Promise<FichaIA> {\n  const semVotos = !temVotos(f.votos?.fixacao) || !temVotos(f.votos?.projecao);''','''export async function completarFicha(f: FichaIA): Promise<FichaIA> {\n  const repetidos = await votosDuplicadosNoAcervo(f.nome, f.casa, f.votos?.fixacao, f.votos?.projecao);\n  const semVotos = !temVotos(f.votos?.fixacao) || !temVotos(f.votos?.projecao) || votosSuspeitos(f.votos) || repetidos;''','completar')
once('''Exemplo: {"fixacao": [42, 194, 855, 179, 23], "projecao": [120, 610, 240, 35], "total": 1971, "origem": "fragrantica"}.\nSe o Fragrantica não mostrar os números, use o Parfumo, resenhas e lojas, transforme em porcentagens que somam 100 e use "origem": "estimativa". Nunca devolva zerado.''','''Formato obrigatório: "fixacao" deve ter exatamente 5 inteiros copiados da fonte e "projecao" exatamente 4 inteiros; "total" é o total real encontrado. Nunca copie números desta instrução.\nSe o Fragrantica não mostrar os números, use o Parfumo, resenhas e lojas, transforme em porcentagens coerentes que somam 100 e use "origem": "estimativa". Nunca devolva zerado e nunca reutilize um vetor fixo de exemplo.''','prompt completar')
once('''    if (novos && temVotos(novos.fixacao)) {''','''    const novosDuplicados = novos ? await votosDuplicadosNoAcervo(f.nome, f.casa, novos.fixacao, novos.projecao) : false;\n    if (novos && temVotos(novos.fixacao) && temVotos(novos.projecao) && !votosSuspeitos(novos) && !novosDuplicados) {''','aceite complemento')
once('''  · exemplo: "fixacao": [42, 194, 855, 179, 23], "projecao": [120, 610, 240, 35], "estacoes": {"inverno": 60, "primavera": 410, "verao": 520, "outono": 170}, "dia": 600, "noite": 150.\n  · Se o Fragrantica não mostrar esses números, NÃO deixe zerado: use a fixação e o rastro do Parfumo, as resenhas e as lojas e transforme em porcentagens que somam 100 (ex.: fixação moderada com 5 a 7 h → [5, 15, 55, 20, 5]; estações e dia/noite de 0 a 100) e use origem = "estimativa".''','''  · Cada número precisa vir da pesquisa atual. Nunca copie números exemplificativos ou vetores fixos da instrução.\n  · Se o Fragrantica não mostrar esses números, NÃO deixe zerado: use a fixação e o rastro do Parfumo, as resenhas e as lojas e transforme em porcentagens coerentes que somam 100, concentrando a maior parcela na categoria indicada pelas fontes; estações e dia/noite ficam de 0 a 100. Use origem = "estimativa".''','prompt principal')
once('''    const pronta = finalizar({ ...resto, perfumistas: f.perfumistas ?? [], revisar: f.revisar ?? [], fontes: f.fontes ?? [], forma: f.forma ?? "ret", tampa: /^#[0-9a-f]{6}$/i.test(f.tampa ?? "") ? f.tampa : "#141417", imagem });\n    // votos ou parecidos faltando: a tela pede o complemento em segundo plano (outra chamada, sem travar o cadastro)''','''    const pronta = finalizar({ ...resto, perfumistas: f.perfumistas ?? [], revisar: f.revisar ?? [], fontes: f.fontes ?? [], forma: f.forma ?? "ret", tampa: /^#[0-9a-f]{6}$/i.test(f.tampa ?? "") ? f.tampa : "#141417", imagem });\n    const duplicados = await votosDuplicadosNoAcervo(pronta.nome || c.nome, pronta.casa || c.casa, pronta.votos?.fixacao, pronta.votos?.projecao);\n    const saneada = duplicados ? invalidarVotos(pronta) : pronta;\n    // votos faltando ou suspeitos: a tela pede o complemento em segundo plano (outra chamada, sem travar o cadastro)''','saneamento')
once('''    const traduzida = await traduzirSobras(pronta);\n    return { ...traduzida, acorde: traduzida.acordes[0] ? acordePrincipal(acordePT(traduzida.acordes[0].nome)) : traduzida.acorde, completar: !temVotos(pronta.votos?.fixacao) || !temVotos(pronta.votos?.projecao), fragrantica: link };''','''    const traduzida = await traduzirSobras(saneada);\n    return { ...traduzida, acorde: traduzida.acordes[0] ? acordePrincipal(acordePT(traduzida.acordes[0].nome)) : traduzida.acorde, completar: !temVotos(saneada.votos?.fixacao) || !temVotos(saneada.votos?.projecao), fragrantica: link };''','retorno')
p.write_text(s)
